version: '3'
services:
  bbs-mariadb:
    container_name: bbs-mariadb
    image: mariadb
    environment:
      MYSQL_DATABASE: bbs
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - ./sql:/docker-entrypoint-initdb.d 
    networks:
      - bbs-net

  bbs-api:
    container_name: bbs-api
    build: .
    image: bbs-api
    depends_on:
      - bbs-mariadb
    networks:
      - bbs-net
    ports:
      - 8000:8000

networks:
  bbs-net:
    driver: bridge
